# Generated by Django 3.0.8 on 2020-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_dob', models.DateField()),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OTH', 'Others')], max_length=10)),
                ('user_phonenumber', models.IntegerField()),
                ('user_city', models.CharField(max_length=50)),
                ('user_state', models.CharField(max_length=50)),
            ],
        ),
    ]
