# Generated by Django 3.0.8 on 2020-08-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200809_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='user_gender',
            field=models.CharField(max_length=10),
        ),
    ]
