# Generated by Django 3.0.8 on 2020-08-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200810_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_name', models.CharField(max_length=1024)),
                ('cart_image', models.ImageField(upload_to='None')),
                ('cart_price', models.PositiveIntegerField()),
                ('cart_publisher', models.CharField(max_length=1024)),
                ('cart_origin', models.CharField(max_length=1024)),
                ('cart_description', models.TextField()),
                ('cart_slug', models.SlugField()),
            ],
        ),
    ]
