# Generated by Django 3.0.8 on 2020-08-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_addtocart_cart_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
