# Generated by Django 3.0.8 on 2020-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_addtocart_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='cart_image',
            field=models.ImageField(upload_to='cart'),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='cart_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
