# Generated by Django 3.0.8 on 2020-08-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200811_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='cart_image',
            field=models.ImageField(upload_to='cartimages/'),
        ),
    ]
