# Generated by Django 3.0.5 on 2020-08-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_addtocart_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='cart_total_price',
        ),
    ]
