# Generated by Django 3.0.8 on 2020-08-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_addtocart_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='user_address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
