# Generated by Django 3.0.8 on 2020-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200813_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='cart_total_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
