# Generated by Django 3.0.8 on 2020-08-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_addtocart_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='cart_total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
