# Generated by Django 3.0.8 on 2020-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200814_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='user_dob',
            field=models.CharField(max_length=10),
        ),
    ]
