# Generated by Django 3.0.5 on 2020-08-19 17:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200815_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_useremail', models.EmailField(default=None, max_length=254)),
                ('order_name', models.CharField(max_length=1024)),
                ('order_image', models.ImageField(upload_to='orderimages/')),
                ('order_price', models.PositiveIntegerField()),
                ('order_publisher', models.CharField(max_length=1024)),
                ('order_origin', models.CharField(max_length=1024)),
                ('order_description', models.TextField()),
                ('order_quantity', models.PositiveIntegerField(default=1)),
                ('order_total_price', models.PositiveIntegerField(default=0)),
                ('order_delivery_date', models.DateTimeField(default=accounts.models.return_datetime)),
            ],
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='cart_slug',
        ),
    ]
