# Generated by Django 3.0.5 on 2020-08-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_order_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_phonenumber',
            field=models.IntegerField(default=9912341234),
        ),
    ]
