# Generated by Django 3.1.5 on 2021-01-27 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210126_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 8, 12, 16, 181533)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_phonenumber',
            field=models.IntegerField(default=9061325108),
        ),
    ]
