# Generated by Django 3.1.5 on 2021-01-30 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210130_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_username',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 20, 25, 12, 58486)),
        ),
    ]
