# Generated by Django 3.1.5 on 2021-01-31 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20210130_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 7, 30, 45, 500643)),
        ),
    ]
