# Generated by Django 3.1.5 on 2021-01-31 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20210131_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 15, 18, 57, 569753)),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentstatus',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
