# Generated by Django 3.1.5 on 2021-02-01 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210201_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 19, 41, 14, 689196)),
        ),
        migrations.AlterField(
            model_name='product',
            name='porder_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 19, 41, 14, 691196)),
        ),
    ]
