# Generated by Django 3.1.5 on 2021-02-01 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20210201_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 20, 9, 21, 90089)),
        ),
        migrations.AlterField(
            model_name='product',
            name='porder_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 20, 9, 21, 90089)),
        ),
    ]
