# Generated by Django 3.1.5 on 2021-02-02 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20210201_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='porder_delivery_date',
            new_name='product_delivery_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='porder_domain',
            new_name='product_domain',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='porder_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='porder_origin',
            new_name='product_origin',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='porder_phonenumber',
            new_name='product_phonenumber',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='porder_price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='porder_publisher',
            new_name='product_publisher',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='porder_useremail',
            new_name='product_useremail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='porder_ordered_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ppaymentstatus',
        ),
        migrations.AddField(
            model_name='product',
            name='product_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 18, 21, 41, 568125)),
        ),
        migrations.AddField(
            model_name='product',
            name='product_selected',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 18, 21, 41, 568125)),
        ),
    ]
