# Generated by Django 3.1.5 on 2021-02-02 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20210202_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 22, 23, 17, 735572)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 22, 23, 17, 735572)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_phonenumber',
            field=models.IntegerField(),
        ),
    ]
