# Generated by Django 3.1.5 on 2021-02-03 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20210203_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_selected',
        ),
        migrations.AddField(
            model_name='product',
            name='product_blog',
            field=models.CharField(default='unselect', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_contact',
            field=models.CharField(default='unselect', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_event',
            field=models.CharField(default='unselect', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_home',
            field=models.CharField(default='unselect', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_login',
            field=models.CharField(default='unselect', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_news',
            field=models.CharField(default='unselect', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_product',
            field=models.CharField(default='unselect', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_shop',
            field=models.CharField(default='unselect', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 10, 6, 15, 461102)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 10, 6, 15, 461102)),
        ),
    ]
