# Generated by Django 3.1.5 on 2021-02-03 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20210203_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 10, 24, 10, 625798)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_blog',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 10, 24, 10, 626796)),
        ),
    ]
