# Generated by Django 3.0.8 on 2020-07-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1024)),
                ('item_image', models.ImageField(upload_to=None)),
                ('item_price', models.PositiveIntegerField()),
                ('item_publisher', models.PositiveIntegerField()),
                ('item_origin', models.CharField(max_length=1024)),
            ],
        ),
    ]
