# Generated by Django 3.0.8 on 2020-07-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_publisher',
            field=models.CharField(max_length=1024),
        ),
    ]
