# Generated by Django 3.0.8 on 2020-08-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(default='This is where description of item exists'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_slug',
            field=models.SlugField(default='description'),
            preserve_default=False,
        ),
    ]
