# Generated by Django 3.0.5 on 2020-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_publisher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
